# Generated by Django 3.2.4 on 2023-06-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkbox_status', models.BooleanField(default=False)),
                ('service_title', models.CharField(max_length=60)),
                ('price', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=60)),
                ('details', models.CharField(max_length=200)),
                ('final_price', models.CharField(max_length=60)),
                ('payment_status', models.BooleanField(default=False)),
                ('services_list', models.ManyToManyField(related_name='services', to='bubblego_backend.Service')),
            ],
        ),
    ]
